# Generated by Django 4.2.5 on 2023-09-21 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglog",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="дата и время попытки",
            ),
        ),
    ]
