# Generated by Django 4.2.5 on 2023-09-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_alter_mailinglog_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата и время попытки"
            ),
        ),
    ]
